# Generated by Django 5.1 on 2024-08-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_fantasy', models.CharField(blank=True, max_length=150, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('carros_Trabalha', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
