# Generated by Django 5.1 on 2024-08-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mecanico', '0001_initial'),
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='carros_Trabalha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CarroQue_trabalha', to='carros.brand'),
        ),
    ]
