# Generated by Django 5.1 on 2024-08-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mecanico', '0002_alter_mecanico_carros_trabalha'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='Foto_Estabelecimento',
            field=models.ImageField(blank=True, null=True, upload_to='Mecanico/Foto_estabelecimento/'),
        ),
    ]
