# Generated by Django 5.1 on 2024-08-27 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mecanico', '0003_mecanico_foto_estabelecimento'),
        ('carros', '0003_cidade_car_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cidades_Mecanico', to='carros.cidade'),
        ),
    ]
