# Generated by Django 5.1 on 2024-09-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mecanico', '0005_mecanicoregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='informacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
